---
driver:
  name: docker
  binary: /usr/bin/docker
  use_sudo: false

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: false

verifier:
  name: inspec

platforms:
  - name: centos

suites:
  - name: InstallDocker
    run_list:
      - recipe[Docker_Cookbook::InstallDocker]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
